/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ittapiros;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Imi
 */
public class felulet extends javax.swing.JFrame {

    /**
     * Creates new form felulet
     */
    private static int randszam;
    private static boolean uj;
    private static boolean nyert;
    public felulet() throws IOException 
    {
        initComponents();
        vizsgal();
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPohar1 = new javax.swing.JButton();
        btnPohar2 = new javax.swing.JButton();
        btnPohar3 = new javax.swing.JButton();
        jchbTippenkentUjhely = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jlbTalalatVisszajelzo = new javax.swing.JLabel();
        btnMent = new javax.swing.JButton();
        btnBetölt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miUjatek = new javax.swing.JMenuItem();
        miBetoltes = new javax.swing.JMenuItem();
        miMentes = new javax.swing.JMenuItem();
        jmJatek = new javax.swing.JMenu();
        mi3Pohar = new javax.swing.JMenuItem();
        mi4Pohar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPohar1.setText("Pohar1");
        btnPohar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohar1ActionPerformed(evt);
            }
        });

        btnPohar2.setText("Pohar2");
        btnPohar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohar2ActionPerformed(evt);
            }
        });

        btnPohar3.setText("Pohar3");
        btnPohar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPohar3ActionPerformed(evt);
            }
        });

        jchbTippenkentUjhely.setSelected(true);
        jchbTippenkentUjhely.setText("TippenkentUjhely");
        jchbTippenkentUjhely.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbTippenkentUjhelyActionPerformed(evt);
            }
        });

        jLabel3.setText("Találat:");

        jlbTalalatVisszajelzo.setText("Nem");

        btnMent.setText("Mentés");
        btnMent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMentActionPerformed(evt);
            }
        });

        btnBetölt.setText("Betöltés");
        btnBetölt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetöltActionPerformed(evt);
            }
        });

        jMenu1.setText("Fajl");

        miUjatek.setText("Uj jatek");
        miUjatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUjatekActionPerformed(evt);
            }
        });
        jMenu1.add(miUjatek);

        miBetoltes.setText("Betoltes");
        jMenu1.add(miBetoltes);

        miMentes.setText("Mentes");
        jMenu1.add(miMentes);

        jMenuBar1.add(jMenu1);

        jmJatek.setText("Jatek");

        mi3Pohar.setText("3 pohar");
        jmJatek.add(mi3Pohar);

        mi4Pohar.setText("4 pohar");
        mi4Pohar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi4PoharActionPerformed(evt);
            }
        });
        jmJatek.add(mi4Pohar);

        jMenuBar1.add(jmJatek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbTalalatVisszajelzo)
                        .addGap(192, 192, 192)
                        .addComponent(jchbTippenkentUjhely))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPohar1)
                                .addGap(40, 40, 40)
                                .addComponent(btnPohar2))
                            .addComponent(btnMent))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPohar3)
                            .addComponent(btnBetölt))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jchbTippenkentUjhely)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbTalalatVisszajelzo))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPohar1)
                    .addComponent(btnPohar2)
                    .addComponent(btnPohar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMent)
                    .addComponent(btnBetölt))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPohar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohar1ActionPerformed
        // TODO add your handling code here:
        
        int szam=1;
        if (szam==randszam)
        {
            jlbTalalatVisszajelzo.setText("IGEN");
            nyert=true;
            
        }
         if (jchbTippenkentUjhely.isSelected())
        {
            jatekindit();
            
        }
       
        
    }//GEN-LAST:event_btnPohar1ActionPerformed

    private void btnPohar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohar2ActionPerformed
        // TODO add your handling code here:
        int szam=2;
        if (szam==randszam)
        {
            jlbTalalatVisszajelzo.setText("IGEN");
            nyert=true;
        }
        if (jchbTippenkentUjhely.isSelected())
        {
            jatekindit();
            
        }
       
        
    }//GEN-LAST:event_btnPohar2ActionPerformed

    private void btnPohar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPohar3ActionPerformed
        // TODO add your handling code here:
        int szam=3;
        if (szam==randszam)
        {
            jlbTalalatVisszajelzo.setText("IGEN");
            nyert=true;
            
        }
        if (jchbTippenkentUjhely.isSelected())
        {
            jatekindit();
            
        }
       
        
    }//GEN-LAST:event_btnPohar3ActionPerformed

    private void jchbTippenkentUjhelyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbTippenkentUjhelyActionPerformed
        
       
    }//GEN-LAST:event_jchbTippenkentUjhelyActionPerformed

    private void miUjatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUjatekActionPerformed
        // TODO add your handling code here:
        
        jatekindit();
        
        
    }//GEN-LAST:event_miUjatekActionPerformed

    private void mi4PoharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi4PoharActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this,"a funkcio nem lerheto");
    }//GEN-LAST:event_mi4PoharActionPerformed

    private void btnMentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMentActionPerformed
       
        int golyoHelye=randszam;
        boolean nyertbool=nyert;
           try {
      FileWriter fajlIro = new FileWriter("config.txt");
      fajlIro.write(golyoHelye+","+nyertbool);
      fajlIro.close();
      System.out.println("kiirva");
      
    } catch (IOException e)
    {
      System.out.println("Hiba.");
      e.printStackTrace();
    }
  

           
        
        
   
    }//GEN-LAST:event_btnMentActionPerformed

    private void btnBetöltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetöltActionPerformed
       
        
        try 
        {
            Path vonal=Paths.get("config.txt");
            List<String> sorlista=Files.readAllLines(vonal);
            Path vonal2=Paths.get("Mentes.txt");
            
            for (String string : sorlista)
            {
               String[] tomb=string.split(",");
               randszam=Integer.parseInt(tomb[0]);
               if (Boolean.parseBoolean(tomb[1])==true)
               {
                   nyert=true;
                    
               }
                
                
            }
        } 
        catch (IOException ex) 
        {
           
        }
            
           
            
        
        
        
    }//GEN-LAST:event_btnBetöltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new felulet().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(felulet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBetölt;
    private javax.swing.JButton btnMent;
    private javax.swing.JButton btnPohar1;
    private javax.swing.JButton btnPohar2;
    private javax.swing.JButton btnPohar3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBox jchbTippenkentUjhely;
    private javax.swing.JLabel jlbTalalatVisszajelzo;
    private javax.swing.JMenu jmJatek;
    private javax.swing.JMenuItem mi3Pohar;
    private javax.swing.JMenuItem mi4Pohar;
    private javax.swing.JMenuItem miBetoltes;
    private javax.swing.JMenuItem miMentes;
    private javax.swing.JMenuItem miUjatek;
    // End of variables declaration//GEN-END:variables

    private void jatekindit()
    {
        
        
        
            Random rnd = new Random();
            randszam = rnd.nextInt(4);
            if (randszam==0)
            {
                randszam+=1;
                
            }
            System.out.println(randszam);
            
        
       
           
        
    }

    private void vizsgal() throws IOException
    {
        try 
        {
            Path vonal=Paths.get("tipp.deb");
            List<String> sorlista=Files.readAllLines(vonal);
            
            this.setTitle(""+randszam);
   
            
          
        } 
        catch (FileNotFoundException e) 
        {
            System.out.println("nincs meg a file");
           
        }
            
    }

  
}
